### PR TITLE
Add a MonadZip instance

### PR DESCRIPTION
**Pull request by treeowl**

### CODE REVIEW

**Comment by treeowl** [comment]
Question: Can we avoid converting the first argument to `ML`? Avoiding both would involve some equally inefficient and far more complicated thing with hyperfunctions or similar, presumably, and I wouldn't want to get into that. A similar question is whether we can avoid one of the two conversions in `traverse`.

**Comment by treeowl** [comment]
I'm not at all sure that avoiding conversion of the first argument would be worth the added complexity and risk of bug introduction; it's just a thought.

**Comment by treeowl** [comment]
Also: can we simplify `munzip` to this?

```haskell
instance MonadZip m => MonadZip (LogicT m) where
  mzipWith f xs ys = fromML $ zipWithML f (toML xs) (toML ys)
  munzip (LogicT f) = case munzip (f corns2 (pure (empty, empty))) of
      (p, q) -> (join (lift p), join (lift q))
    where
      corns2 :: Monad m
        => (a, b) -> m (LogicT m a, LogicT m b) -> m (LogicT m a, LogicT m b)
      corns2 (a, b) m = m >>= \(as, bs) -> pure (pure a <|> as, pure b <|> bs)
```

That's certainly cleaner; let me think about that.

**Comment by treeowl** [comment]
Yes, we can do something almost like that `munzip`; we just need to be slightly lazier. I'll do that.

**Comment by treeowl** [comment]
OK, I streamlined `munzip`, and I removed the *outer* conversion from `mzipWith`. I have the feeling there's probably a way to remove the first inner conversion, but it's currently beyond me.

**Comment by treeowl** [comment]
Hrmph. I'm not actually convinced that this fancy `munzip` is faster (and not slower) than the one that goes through `ML` in both directions. Let's just do the simple thing for now.

**Comment by Bodigrim** [comment]
Nice!

**Pull request merged**
